name: decaf
description: "Quit caffeine fast."
publish_to: 'none'
version: 2025.07.19+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  sembast: ^3.8.5+1
  flutter_riverpod: ^2.6.1
  fl_chart: ^1.0.0
  path_provider: ^2.1.5
  path: ^1.9.1
  intl: ^0.20.2
  uuid: ^4.5.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
